## Array

Esta estrutura serve para armazenar conjuntos de dados ordenados na memória

In [18]:
import numpy as np

In [21]:
npa = np.array(range(10))
npa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a = np.array(range(6))
b = np.ones(5)
print(a)
print(b)


[0 1 2 3 4 5]
[1. 1. 1. 1. 1.]


In [12]:
conct = np.concatenate([a,b])
conct

array([0., 1., 2., 3., 4., 5., 1., 1., 1., 1., 1.])

In [15]:
splitado = np.split(conct,[2])
pt1,pt2 = splitado
print(pt1)
print(pt2)

[0. 1.]
[2. 3. 4. 5. 1. 1. 1. 1. 1.]


In [26]:
conct.mean()
conct.sum()
conct.max()
np.median(conct)
np.var(conct)

2.148760330578512

In [29]:
from skimage import io
from matplotlib.pyplot as plt
photo = io.imread('eu.jpg')
type(photo)


numpy.ndarray